name: Build VitaCast VPK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
        
    - name: Setup VitaSDK
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget
        wget -q https://github.com/vitasdk/autobuilds/releases/download/master-linux-v1200/vitasdk-x86_64-linux-gnu-2022-06-08_12-10-10.tar.bz2 || exit 1
        sudo tar -xf vitasdk-x86_64-linux-gnu-2022-06-08_12-10-10.tar.bz2 -C /usr/local/ || exit 1
        echo "VITASDK=/usr/local/vitasdk" >> $GITHUB_ENV
        echo "/usr/local/vitasdk/bin" >> $GITHUB_PATH
        
    - name: Verify tools
      run: |
        export VITASDK=/usr/local/vitasdk
        export PATH=$VITASDK/bin:$PATH
        which arm-vita-eabi-gcc || exit 1
        which vita-mksfoex || exit 1
        which vita-pack-vpk || exit 1
        echo "✓ Todas las herramientas están disponibles"
        
    - name: Build VPK
      run: |
        export VITASDK=/usr/local/vitasdk
        export PATH=$VITASDK/bin:$PATH
        echo "Limpiando build anterior..."
        make -f Makefile clean || true
        echo "Compilando..."
        make -f Makefile || exit 1
        echo "✓ Compilación exitosa"
        ls -lh VitaCast.vpk || exit 1
        echo "✓ VPK generado correctamente"
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: VitaCast.vpk
        generate_release_notes: true
        draft: false
        prerelease: false
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Artifact
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: VitaCast-VPK
        path: VitaCast.vpk
