name: Build VitaCast VPK

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup VitaSDK
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget
        wget https://github.com/vitasdk/autobuilds/releases/download/master-linux-v1200/vitasdk-x86_64-linux-gnu-2022-06-08_12-10-10.tar.bz2
        sudo tar -xf vitasdk-x86_64-linux-gnu-2022-06-08_12-10-10.tar.bz2 -C /usr/local/
        echo "VITASDK=/usr/local/vitasdk" >> $GITHUB_ENV
        echo "/usr/local/vitasdk/bin" >> $GITHUB_PATH
        
    - name: Build
      run: |
        export VITASDK=/usr/local/vitasdk
        export PATH=$VITASDK/bin:$PATH
        ls -la
        make clean
        make
        
    - name: Upload VPK
      uses: actions/upload-artifact@v3
      with:
        name: VitaCast-VPK
        path: VitaCast.vpk
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: VitaCast.vpk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
