name: Build VitaCast VPK

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: gnuton/vitasdk-docker:latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Build
      run: |
        ls -la
        # Verificar que existen los recursos necesarios
        ls -la sce_sys/
        ls -la sce_sys/livearea/contents/
        make clean
        make
        
    - name: Upload VPK
      uses: actions/upload-artifact@v4
      with:
        name: VitaCast-VPK
        path: VitaCast.vpk
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: VitaCast.vpk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
